import Head from "next/head";
import fs from "fs";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { parse } from "exifr";

export default function Home({ pix }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {pix.map(({ fname, width, height }) => {
          return (
            <div key={fname}>
              <a href={`/${fname}`} download>
                <Image
                  src={`/${fname}`}
                  alt="Vercel Logo"
                  width={Math.floor(400)}
                  height={Math.floor((400 * height) / width)}
                />
              </a>
            </div>
          );
        })}
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  let pix = fs
    .readdirSync("./public")
    .filter((f) => f.match(/.*/)?.length > 0)
    .map((f) => f);

  let parseDims = async function (pic) {
    let dims = await parse("public/" + pic, [
      "ExifImageWidth",
      "ExifImageHeight",
    ]);
    return dims;
  };

  let pix_dims = pix.map((pic) => parseDims(pic));
  let m = await Promise.all(pix_dims);
  let pixes = [];

  for (let i = 0; i < pix.length; i++) {
    let item = {
      fname: pix[i],
      width: m[i].ExifImageWidth,
      height: m[i].ExifImageHeight,
    };
    pixes.push(item);
  }
  return { props: { pix: pixes } };
}
